name = "InboundsArrays"
uuid = "fb0a3009-a0ba-48c7-b828-2efdeaae8962"
authors = ["John Omotani <john.omotani@ukaea.uk>"]
version = "0.1.0"

[weakdeps]
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"

[extensions]
MPIExt = "MPI"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
