name = "InboundsArrays"
uuid = "fb0a3009-a0ba-48c7-b828-2efdeaae8962"
authors = ["John Omotani <john.omotani@ukaea.uk>"]
version = "0.2.1"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SparseMatricesCSR = "a0a7dd2c-ebf4-11e9-1f05-cf50bc540ca1"

[weakdeps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"

[extensions]
FFTWExt = "FFTW"
HDF5Ext = "HDF5"
MPIExt = "MPI"
MakieExt = "Makie"
NCDatasetsExt = "NCDatasets"

[compat]
FFTW = "1.5"
HDF5 = "0.17"
LinearAlgebra = "1"
MPI = "0.20"
Makie = "0.22"
NCDatasets = "0.14"
Preferences = "1.4"
SparseArrays = "1.9"
SparseMatricesCSR = "0.6"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
