name = "InboundsArrays"
uuid = "fb0a3009-a0ba-48c7-b828-2efdeaae8962"
authors = ["John Omotani <john.omotani@ukaea.uk>"]
version = "0.1.1"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SparseMatricesCSR = "a0a7dd2c-ebf4-11e9-1f05-cf50bc540ca1"

[weakdeps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"

[extensions]
FFTWExt = "FFTW"
MPIExt = "MPI"

[compat]
FFTW = "1.5"
LinearAlgebra = "1"
MPI = "0.20"
SparseArrays = "1.9"
SparseMatricesCSR = "0.6"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
